### ISSUE TITLE
后台返回什么

### ISSUE THREAD

**Issue by nevermind123456** [zimv/WebSocketHeartBeat#1]
后台要返回什么呢

**Comment by zimv** [comment]
具体是指什么？

**Comment by nevermind123456** [comment]
就是我要后台怎么说呢？我send一个信息给后台，后台要返回给我什么呢

**Comment by zimv** [comment]
心跳的话，后台随便返回一个消息就行了，你这边不处理那个消息就行了，只要后台返回回来了，就说明连接是正常的

**Comment by zimv** [comment]
只要你收到任何消息 都说明连接是正常的

**Comment by nevermind123456** [comment]
嗯嗯 好的好的，只要跟后台说一下随便返回一个东西就好了是吧？

**Comment by zimv** [comment]
反之，你发送心跳，后端返回了你没收到，或者后端直接发现和你的链接断开了，那你都没有收到消息，就说明断开了

**Comment by nevermind123456** [comment]
怎么判断我是否收到后台返回的信息呢？

**Comment by zimv** [comment]
onmessage拿到消息就行了呀，只要拿到消息了，就说明连接还是对的呀

**Comment by zimv** [comment]
send心跳之后不是会有个定时器吗，如果超过时间还没收到消息，就说明断开了

**Comment by nevermind123456** [comment]
如果服务断开 是不是一直去发送请求呢？我看到的是一直发送请求的

**Comment by zimv** [comment]
是啊，一直发送直到能连接上服务器，如果是你自己断网了，也会一直发送，直到你网络恢复

**Comment by nevermind123456** [comment]
如果是404呢？

**Comment by zimv** [comment]
404和没连上是一样的

**Comment by nevermind123456** [comment]
我这里404是只发了一遍请求啊

**Comment by zimv** [comment]
没有404这种状态吧？你报错是啥 复制给我看看

**Comment by nevermind123456** [comment]
那会是我自己的地址写错了，你能告诉我应该怎么检测自己的代码是否正确啊

**Comment by nevermind123456** [comment]
我不知道怎么检测自己写的断开连接是否正确，因为我这里现在ws是连接上的，状态是正常的

**Comment by zimv** [comment]
断网
